### ISSUE TITLE
If the type is "any" no definition is printed

### ISSUE THREAD

**Issue by 21stio** [YousefED/typescript-json-schema#52]
```
export interface IResultResponse {
    success:boolean;
    message?:string;
    data?:any;
}
```

turns  into 

```
IResultResponse:
  type: object
  properties:
    success:
      type: boolean
    message:
      type: string
    data:
  additionalProperties: false
  required:
    - success
```
